### ISSUE TITLE
Could not load 'cimgui'.

### ISSUE THREAD

**Issue by ZekusV** [CEO-Chair/TerraAngel#10]
Error when trying to open TerraAngel.

![image](https://user-images.githubusercontent.com/112866998/193888900-ee5c64ac-5f00-4c39-b85f-b70082ebe5e3.png)

**Comment by CEO-Chair** [comment]
"im working on it"

**Comment by CEO-Chair** [comment]
fixed with [b20d236](https://github.com/CEO-Chair/TerraAngel/commit/b20d236520f15b099b809ce028369c4d03900203)
