### ISSUE TITLE
there is no file in src\TerraAngel\Terraria\bin\Release\net6.0

### ISSUE THREAD

**Issue by WhyWeStillHer** [CEO-Chair/TerraAngel#12]
Which branch should i downloaded
I download the first one there is no file
I download 1.4.4.4 there is file but i csnt open terraria
Help me

**Comment by Azazel131** [comment]
Me and multiple other people are also getting this

**Comment by Azazel131** [comment]
also discord link is expired

**Comment by CEO-Chair** [comment]
make sure you're on the latest commit, if that doesn't work then upload your build_log.txt here

**Comment by CEO-Chair** [comment]
> arsenic is gay

true

**Comment by WhyWeStillHer** [comment]
it worked now tysm
