### ISSUE TITLE
Build still does not appear in bin\Release\net6.0

### ISSUE THREAD

**Issue by Azazel131** [CEO-Chair/TerraAngel#13]
fast_start.bat works fine, there is just no output

**Comment by CEO-Chair** [comment]
make sure you're on the latest branch and on the latest commit 
if that doesn't work then upload your build_log.txt here

**Comment by Azazel131** [comment]
[build_log.txt](https://github.com/CEO-Chair/TerraAngel/files/9738201/build_log.txt)
