### ISSUE TITLE
Can't build TerraAngel

### ISSUE THREAD

**Issue by Cleetusterra** [CEO-Chair/TerraAngel#18]
Whenever I try to run fast_start.bat it opens for a few seconds then closes and doesn't create a new folder

**Comment by CEO-Chair** [comment]
do you have the dotnet 6.0 sdk installed?

**Comment by Cleetusterra** [comment]
yes i downloaded that before trying to install it

**Comment by CEO-Chair** [comment]
did you restart your computer after installing it?

**Comment by Cleetusterra** [comment]
yes

**Comment by CEO-Chair** [comment]
hmm, open up command prompt and go to the directory where the fast start is, and run it from there

**Comment by Cleetusterra** [comment]
ok

**Comment by CEO-Chair** [comment]
![image](https://user-images.githubusercontent.com/87276335/196054280-08329014-6e8e-44e0-b003-1193774e9a02.png)

**Comment by CEO-Chair** [comment]
you also need to add `--branch dev-1.4.4.5` when cloning if you're using Terraria 1.4.4.5

**Comment by Cleetusterra** [comment]
![image](https://user-images.githubusercontent.com/69166578/196054350-9043043c-9cc2-4624-a2b8-2c9b5699cfd1.png)

**Comment by Cleetusterra** [comment]
> you also need to add `--branch dev-1.4.4.5` when cloning if you're using Terraria 1.4.4.5

that might be the problem

**Comment by CEO-Chair** [comment]
maybe

**Comment by Cleetusterra** [comment]
so just git clone https://github.com/CEO-Chair/TerraAngel.git --recursive --branch dev-1.4.4.5

**Comment by CEO-Chair** [comment]
also make sure you clone in a place like your desktop, dont use C:\Windows\Sytem32

**Comment by Cleetusterra** [comment]
> also make sure you clone in a place like your desktop, dont use C:\Windows\Sytem32

how do i change where it clones

**Comment by CEO-Chair** [comment]
eg, cd C:\Users\you\Desktop

**Comment by CEO-Chair** [comment]
and then clone

**Comment by Cleetusterra** [comment]
ok

**Comment by Cleetusterra** [comment]
that worked

**Comment by Cleetusterra** [comment]
thanks

**Comment by CEO-Chair** [comment]
yeah
