### ISSUE TITLE
Does the software support multiple languages?

### ISSUE THREAD

**Issue by Shuazijun** [CEO-Chair/TerraAngel#22]
Does the software support multiple languages?  
When the game language is set to Simplified Chinese and Traditional Chinese, the chat bar cannot display the correct content, and all Chinese characters are incorrectly displayed as? number

**Comment by Shuazijun** [comment]
Error like this  
![image](https://user-images.githubusercontent.com/30001049/197576413-1bfc19f4-de35-48be-8d61-6c3f49bc2515.png)
![image](https://user-images.githubusercontent.com/30001049/197576414-d1ce5197-14c0-442c-ba3f-f5ed81c86f49.png)

**Comment by CEO-Chair** [comment]
I currently do not plan to support any languages besides English in the near future.
