### ISSUE TITLE
Installation Error 

### ISSUE THREAD

**Issue by LaquanFinema** [CEO-Chair/TerraAngel#27]
git clone https://github.com/CEO-Chair/TerraAngel.git --recursive
Cloning into 'TerraAngel'...
remote: Enumerating objects: 3441, done.
remote: Counting objects: 100% (549/549), done.
remote: Compressing objects: 100% (381/381), done.
error: RPC failed; curl 56 OpenSSL SSL_read: Connection was reset, errno 10054
error: 7364 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output

**Comment by CEO-Chair** [comment]
you can try to do `git config http.postBuffer 524288000`
