### ISSUE TITLE
Anything new?

### ISSUE THREAD

**Issue by TruePowerSyao** [CEO-Chair/TerraAngel#30]
there will be such plugins as copying other people's inventories?
Edit: i'm very bad at english

**Comment by CEO-Chair** [comment]
What?

**Comment by TruePowerSyao** [comment]
I mean, there will be such plugins as copying other people's inventories?

**Comment by CEO-Chair** [comment]
Plugins are meant to be user-created extensions of the client.

**Comment by TruePowerSyao** [comment]
But will you do this as in client?

**Comment by CEO-Chair** [comment]
There will be things added to the client, but I have no plans to add "copying other people's inventories"
