### ISSUE TITLE
Zoom issues at higher resolutions

### ISSUE THREAD

**Issue by sk4rm** [CEO-Chair/TerraAngel#33]
Terraria version: `1.4.4.9`
TerraAngel version: https://github.com/CEO-Chair/TerraAngel/commit/3319f8c7201ec85da6c79a2a4e91583b1a747a73

<hr>

Initial zoom levels (100%) here differ from vanilla.

### Vanilla, 2880x1800 (16:10), borderless window, zoom: 100%, UI scale: 100%:
<img src="https://user-images.githubusercontent.com/74897601/210158445-58c96762-5006-44ae-b74d-ca9367ae80d9.png" height=400>

### TerraAngel, 2880x1800 (16:10), borderless window, zoom: 100%, UI scale: 100%:
<img src="https://user-images.githubusercontent.com/74897601/210158239-a67fe782-51a7-4f9a-b73f-e5b59d9db9d2.png" height=400>

### TerraAngel, 2880x1800 (16:10), windowed, main menu (not cropped)
<img src="https://user-images.githubusercontent.com/74897601/210158545-30ca2d35-9218-4efd-a6d6-9eea36e90e56.png" height=400>

<hr>

There are also some misaligned texts under Settings Menu > Video:
<img src="https://user-images.githubusercontent.com/74897601/210158243-72b33a44-32be-46b6-8b0b-dc48e0656e37.png" height=400>

**Comment by CEO-Chair** [comment]
Alright, I'll look into this tomorrow.

**Comment by CEO-Chair** [comment]
I am unable to reproduce the zoom issue on 3440x1440

![image](https://user-images.githubusercontent.com/87276335/210264757-de54cdcd-962b-4b15-a23f-4d500d870138.png)
![image](https://user-images.githubusercontent.com/87276335/210264763-92e63392-95df-444b-babe-f6a225beef4c.png)

**Comment by CEO-Chair** [comment]
I am similarly unable to reproduce this bug on 1600x1000
![image](https://user-images.githubusercontent.com/87276335/210265039-cf25ae91-1db3-48de-8657-55ebdf810f53.png)
![image](https://user-images.githubusercontent.com/87276335/210265034-3a52ca03-5f90-40ad-8618-2bca496dba39.png)

**Comment by CEO-Chair** [comment]
Same goes for fullscreen and borderless windowed

**Comment by sk4rm** [comment]
I messed around with my Windows display resolutions and found that it seems to be affected by the scaling.

<img src="https://user-images.githubusercontent.com/74897601/210273422-cd44801e-434e-407e-9de7-1269f2de2c1a.png" width=800>

I normally use 200% scaling but at 100% it works fine, with the caveat that TerraAngel's UI and everything else outside the game becomes tiny.

<img src="https://user-images.githubusercontent.com/74897601/210273655-93700af7-c9ad-4cea-9af0-50ba78fb85e6.png" width=800>

**Comment by sk4rm** [comment]
I think I found a fix: by overriding the scaling to be performed by the application.

<img src="https://user-images.githubusercontent.com/74897601/210275016-14af3b5f-dda1-47c6-b885-84eafb04d8d7.png" width=800>

### Results

<img src="https://user-images.githubusercontent.com/74897601/210275168-ee989d69-5611-4519-b100-9ec355d7892a.png" width=800>

<img src="https://user-images.githubusercontent.com/74897601/210275228-58cf8648-46b7-451e-bc97-70da9a36e0ec.png" width=800>

TerraAngel's UI still very small, however, albeit still usable.

**Comment by CEO-Chair** [comment]
This may be an issue with the backend for windowing in TerraAngel being different than the normal game
