### ISSUE TITLE
src/TerraAngel/Terraria/bin/Release/net7.0/  directory does not build when using 'fast_start.bat'

### ISSUE THREAD

**Issue by ZekusV** [CEO-Chair/TerraAngel#36]
After using fast_start.bat the bin folder never appears, starting fast_start.bat shows this and the rest of the usual build process, but bin never appears.

![image](https://user-images.githubusercontent.com/112866998/220782890-63ad74ad-7d8e-43ee-bd7a-f0cd6fe8ce91.png)

**Comment by CEO-Chair** [comment]
Upload your `build_log.txt`. This git error is unrelated.
