### ISSUE TITLE
Can't build TerraAngel

### ISSUE THREAD

**Issue by TruePowerSyao** [CEO-Chair/TerraAngel#37]
fatal: remote error: upload-pack: not our ref dfc20aab2bab3bf95cf5e13fc2f5410ad22eb74c
fatal: Fetched in submodule path 'TNA', but it did not contain dfc20aab2bab3bf95cf5e13fc2f5410ad22eb74c. Direct fetching of that commit failed.
This is what i see, when trying to copy TerraAngel

**Comment by TruePowerSyao** [comment]
![Help](https://user-images.githubusercontent.com/121280337/221354463-e2f55659-9e8f-49ba-9fd4-9bc7e78ef86d.png)
This is error from opening fast-start.bat file

**Comment by CEO-Chair** [comment]
Should be fixed in https://github.com/CEO-Chair/TerraAngel/commit/21684aba403e3c71e521a17f2f35919fc3439ca2
