### ISSUE TITLE
Massive Fail

### ISSUE THREAD

**Issue by Devonsnow514** [CEO-Chair/TerraAngel#39]
[terra.txt](https://github.com/CEO-Chair/TerraAngel/files/11011746/terra.txt)

I have no clue what any of this means lol but this was my output log

**Comment by punchready** [comment]
MASSIVE FAIL

**Comment by CEO-Chair** [comment]
Do you have Terraria properly installed?
Try running `xnafx40_redist.msi` located in your Terraria directory (usually `C:\Program Files (x86)\Steam\steamapps\common\Terraria`), restarting your computer, and running the setup again.

**Comment by CEO-Chair** [comment]
MASSIVE FAIL

**Comment by steviegt6** [comment]
MASSIVE FAIL

**Comment by Devonsnow514** [comment]
still dont work
