### ISSUE TITLE
Steam Client

### ISSUE THREAD

**Issue by dark22** [CEO-Chair/TerraAngel#43]
How can I resolve the request to launch via the Steam client?

**Comment by CEO-Chair** [comment]
What do you mean?

**Comment by CEO-Chair** [comment]
You can try restarting your computer or restarting the steam client. If you do not have Terraria purchased on steam, then...

**Comment by dark22** [comment]
Sorry for the delay in getting back. Is that the modified app should be used in the same folder as the game? Because a while ago when I tested this modification, I just built it and went to the output folder and ran the application without any problems. It now requests the Steam client, so I'm asking if there have been any changes in that regard. I own the original game through Steam. Thank you for your attention to this project.

**Comment by CEO-Chair** [comment]
There were some changes regarding steam a bit ago, but they should just work without any issues. It is possible to disable steam support by modifying your `clientConfig.json` file (probably located in `C:\Users\...\Documents\My Games\Terraria\TerraAngel\clientConfig.json`)
Open the file and change this:
![image](https://user-images.githubusercontent.com/87276335/230786123-1b0bf7b2-3cc1-45ef-98a0-3fc0ba13b44d.png)
to false
