### ISSUE TITLE
Console just.. Closes

### ISSUE THREAD

**Issue by Devonsnow514** [CEO-Chair/TerraAngel#46]
Whenever I click fast start, It says Building TerraAngelSetup and it just closes, No logs nothing. I have dotnet sdk 7.0 installed

**Comment by Devonsnow514** [comment]
I uninstalled it, Restarted my pc, Still closes. Im going to try to revo uninstall git and dotnet again and try tommorrow

**Comment by CEO-Chair** [comment]
Please ensure that you are following the Installation guide properly.

**Comment by Devonsnow514** [comment]
I did
