### ISSUE TITLE
Idk what to do after fast_start.bat

### ISSUE THREAD

**Issue by JustARandomName1** [CEO-Chair/TerraAngel#6]
Im stupid so im lost on what to do after i finish fast_start.bat    ive tried opening the terraria in src/TerraAngel/Terraria/bin/Release/net6.0/ folder, but nothing happens, nothing happens when i load terraria either

i think im stupid

**Comment by CEO-Chair** [comment]
what do you mean "nothing happens"? do any errors occur? are both the Terraraia.exe and Terraria.dll files in the net6.0 folder? is the Content folder there too?

**Comment by JustARandomName1** [comment]
everything is there,  but when i open terraria nothing gets loaded apart from the vanilla game, or if i open the terraria in the src/TerraAngel/Terraria/bin/Release/net6.0/ folder straight up nothing happens
no errors

**Comment by CEO-Chair** [comment]
ok i just pushed a commit that should display an error now, try running fast_update.bat and fast_compile.bat

**Comment by JustARandomName1** [comment]
![image](https://user-images.githubusercontent.com/87848632/182953276-6fd4b15c-8035-497e-ad0a-850f22e1f99b.png)

im clicking on it and still literally nothing happens nor does anything happen when i launch vanilla terraria

**Comment by CEO-Chair** [comment]
did you do the update and recompile steps?

**Comment by CEO-Chair** [comment]
FNA requires at least opengl 3 i think

**Comment by JustARandomName1** [comment]
yes i updated and recompiled, ill check for opengl 3

**Comment by CEO-Chair** [comment]
actually it might be an error on my end with settings
![image](https://user-images.githubusercontent.com/87276335/182957179-d7be98ce-a381-4feb-b2c4-eaaceff13209.png)

**Comment by JustARandomName1** [comment]
idk i dont understand because ive never touched code

**Comment by CEO-Chair** [comment]
yeah theres a bug with there being not clientConfig file

**Comment by CEO-Chair** [comment]
working on a fix right now

**Comment by JustARandomName1** [comment]
tysm

**Comment by CEO-Chair** [comment]
ok pushed a fixed, try updating & recompiling now

**Comment by JustARandomName1** [comment]
ok

**Comment by JustARandomName1** [comment]
yooooo 
![image](https://user-images.githubusercontent.com/87848632/182958679-1a9b19f0-a635-4982-a706-65a662a9bdaa.png)
it works

**Comment by JustARandomName1** [comment]
Thank you so much!!!!

**Comment by CEO-Chair** [comment]
thanks for reporting this bug to me

**Comment by JustARandomName1** [comment]
also there is a problem where my resolution is stuck at 1440 x 900
![image](https://user-images.githubusercontent.com/87848632/182961499-1beb8ab8-5489-4fa6-b373-6b3a609a904c.png)

**Comment by CEO-Chair** [comment]
you need to press the go windowed button to properly change resolution i think

**Comment by JustARandomName1** [comment]
idk i tried everything but it didnt change
