### ISSUE TITLE
No bin folder

### ISSUE THREAD

**Issue by Staticnoi** [CEO-Chair/TerraAngel#62]
Same problem like #61 and #60 i've tried restarting still gives the same output

**Comment by sors89** [comment]
I don't know much about .net stuff but the reason for this is because TNA.Core.csproj is using net8.0 instead of net7.0, you just need to open it change from net8.0 to net7.0 and run fast_start.bat again, it should work. The game keep crashing for me tho and i have no ideal how to fix it.
