### ISSUE TITLE
The "bin" folder doesn't exists, neither terraria.exe and when running fast_start, the process stops after this:

### ISSUE THREAD

**Issue by Contomy** [CEO-Chair/TerraAngel#66]
Hello, I only made an account here to post my problem, which I noticed many of us are having:

![image](https://github.com/user-attachments/assets/d05a1201-b1a9-4563-8b00-95183cd2dc7f)

I literally pinned this website to my markers, so I can check very often if someone answers, I've heard the issue has something to do with the "net" program but I'm not sure at all (I have 0 idea about coding).

Please I need help fixing this, 100% aware for possible answers and I can provide any further information if needed.

**Comment by chairclr** [comment]
This project is abandoned and does not work.
